### ISSUE TITLE
different ei.h paths

### ISSUE THREAD

**Issue by BenBals** [fhunleth/elixir_ale#31]
I installed my Erlang via homebrew. The Erlang stuff, including ei.h is in `/usr/local/Cellar/erlang/19.0.2/lib/erlang/`. How can I edit the Makefile to include it as a search path?

Thanks in advance.

**Comment by fhunleth** [comment]
It's possible, but you'll get an error shortly after that since your Mac won't have any of the I2C or SPI libraries on it and the GPIO code won't work at runtime. If you have a Raspberry Pi or BeagleBone, I'd recommend building it there or trying out Nerves. If you're already doing that and just want to test on your laptop, most people stub out Elixir ALE. See the FAQ in the README for a good link.

**Comment by BenBals** [comment]
I am using Nerves. What I am trying to do is compiling my Nerves project on
my Mac. I have the crosscompiler and set the flag. Now the Makefile can't
find ei.h because Homebrew installed into a folder different from the paths
searched by the Makefile. I know where it is. How can I tell it to search
the right path?

**Comment by fhunleth** [comment]
Then something else is wrong since ei.h needs to come from the version of Erlang that's going to your target. That comes from the Nerves system image. Another way to think about this is if the C code gets compiled using libraries compiled for OSX (coming from Homebrew), it won't work on your RPi, BBB, or whatever you're using. 

I'm going to be offline for the next 9 hours or so. You might have some luck asking on the nerves channel on the Elixir-lang slack. What you're doing should work out of the box, so I'm a little surprised. Perhaps @mobileoverlord has an idea.

**Comment by mobileoverlord** [comment]
@BenBals do you have an example project which mimics the issue you are having. The Nerves Env should take care of setting the ERL_EI_INCLUDE_DIR and ERL_EI_LIBDIR env variables.

The Makefile is currently laid out to only set them by looking in the search paths if they are not already set `?=`

You can see some additional information regarding your Nerves Env by putting `NERVES_DEBUG=1 mix compile`

**Comment by BenBals** [comment]
Doing a clean git clone fix the problem. Don't know what was wrong. Thanks for your kind help.

**Comment by BenBals** [comment]
Now this is super weird. My app is an umbrella project. I can do `mix test`, `mix compile`, `mix firmware` and so on in `apps/firmware` without any problems, but I can't run `mix test` from the project root. Again the `ei.h` can't be found. The project is open source at https://gitlab.com/vitabox/vitaprog. 

The error:
```
$ mix test 
==> elixir_ale
Makefile:24: *** Could not find include directory for ei.h. Check that Erlang header files are available.  Stop.
could not compile dependency :elixir_ale, "mix compile" failed. You can recompile this dependency with "mix deps.compile elixir_ale", update it with "mix deps.update elixir_ale" or clean it with "mix deps.clean elixir_ale"
** (Mix) Could not compile with "make" (exit status: 2).
Depending on your OS, make sure to follow these instructions:

  * Mac OS X: You need to have gcc and make installed. Try running the
    commands "gcc --version" and / or "make --version". If these programs
    are not installed, you will be prompted to install them.

  * Linux: You need to have gcc and make installed. If you are using
    Ubuntu or any other Debian-based system, install the packages
    "build-essential". Also install "erlang-dev" package if not
    included in your Erlang/OTP version. If you're on Fedora, run
    "dnf group install 'Development Tools'".
```

**Comment by mobileoverlord** [comment]
When commands are executed at the root of an umbrella they are executed in the scope of the umbrella mix environment. This means that the aliases that are defined in your `apps/firmware` project are never invoked, which means Nerves Env is never invoked and it's attempting to run under OS X.

To run test from the top level, use `mix cmd mix test` This will enumerate and execute each app in the umbrella in its own environment.

**Comment by BenBals** [comment]
Thank you. That solves the problem.
