### ISSUE TITLE
HC-SR04 Kernel Module

### ISSUE THREAD

**Issue by idahogray** [fhunleth/elixir_ale#51]
I am back with more questions about the HC-SR04. I did some more searching and came across this kernel module: https://github.com/johannesthoma/linux-hc-sro4.

Would this be the correct project to include that kernel module in? If yes, how would I go about doing that? If not, can you point me to the correct project?

I tried searching for how to include additional kernel modules in nerves projects but didn't find anything.

Again, I really appreciate the help. Feel free to point me to documentation if there is something already available.

**Comment by fhunleth** [comment]
I'm keeping `elixir_ale` very focused only on supporting generic GPIO, I2C, and SPI interfaces on a Linux. The route to go is to create your own Elixir library with all of the docs, etc. for supporting the HC-SR04 if you go the custom kernel module route. I've only built custom kernel modules using Buildroot projects. You could do something similar with a custom Nerves system.

One thing about kernel module projects is that they can be hard to maintain since the Linux kernel's APIs change between kernel versions. I'm not sure that I'd be excited about going down this route.

I think that you should consider going the GrovePi or GrovePi Zero route and buying their distance sensor. It provides distance measurements and there's a GrovePi hex package.
